version: "3.2"
services:
  quotes:
    image: nickumia/quote-scraper:latest
    build:
      context: quotes
    working_dir: /app
    depends_on:
      - "mail"
    volumes:
      - ./app:/app

  mail:
    image: nickumia/mail-server:latest
    build:
      context: mail
    working_dir: /app
    ports:
      - "4444:4444"
    volumes:
      - ./app:/app
